PRAGMA busy_timeout = 3000;
PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS user_account (
	ID_ TEXT PRIMARY KEY,
	EMAIL_ TEXT NOT NULL UNIQUE,
	DISPLAY_NAME_ TEXT NOT NULL,
	AVATAR_URL_ TEXT,
	STATUS_ TEXT NOT NULL DEFAULT 'active',
	CREATED_AT_ TEXT NOT NULL,
	UPDATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT
);

CREATE TABLE IF NOT EXISTS team (
	ID_ TEXT PRIMARY KEY,
	SLUG_ TEXT NOT NULL UNIQUE,
	NAME_ TEXT NOT NULL,
	DESCRIPTION_ TEXT NOT NULL DEFAULT '',
	CREATED_BY_ TEXT,
	UPDATED_BY_ TEXT,
	CREATED_AT_ TEXT NOT NULL,
	UPDATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT
);

CREATE TABLE IF NOT EXISTS team_member (
	TEAM_ID_ TEXT NOT NULL REFERENCES team(ID_),
	USER_ID_ TEXT NOT NULL REFERENCES user_account(ID_),
	ROLE_ TEXT NOT NULL CHECK (ROLE_ IN ('owner','admin','member')),
	INVITED_BY_ TEXT,
	JOINED_AT_ TEXT NOT NULL,
	LEFT_AT_ TEXT,
	PRIMARY KEY (TEAM_ID_, USER_ID_)
);

CREATE TABLE IF NOT EXISTS workflow (
	ID_ TEXT PRIMARY KEY,
	KEY_ TEXT NOT NULL UNIQUE,
	NAME_ TEXT NOT NULL,
	DESCRIPTION_ TEXT NOT NULL DEFAULT '',
	IS_DEFAULT_ INTEGER NOT NULL DEFAULT 0 CHECK (IS_DEFAULT_ IN (0, 1)),
	TRANSITION_MODE_ TEXT NOT NULL DEFAULT 'strict' CHECK (TRANSITION_MODE_ IN ('strict', 'free')),
	CREATED_BY_ TEXT,
	UPDATED_BY_ TEXT,
	CREATED_AT_ TEXT NOT NULL,
	UPDATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT
);

CREATE TABLE IF NOT EXISTS workflow_stage_def (
	ID_ TEXT PRIMARY KEY,
	KEY_ TEXT NOT NULL UNIQUE,
	NAME_ TEXT NOT NULL,
	DESCRIPTION_ TEXT NOT NULL DEFAULT '',
	IS_SYSTEM_ INTEGER NOT NULL DEFAULT 1 CHECK (IS_SYSTEM_ IN (0, 1)),
	CREATED_AT_ TEXT NOT NULL,
	UPDATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT
);

CREATE TABLE IF NOT EXISTS workflow_status_def (
	ID_ TEXT PRIMARY KEY,
	KEY_ TEXT NOT NULL UNIQUE,
	NAME_ TEXT NOT NULL,
	COLUMN_KEY_ TEXT NOT NULL CHECK (COLUMN_KEY_ IN ('backlog','todo','in_progress','in_review','completed')),
	DESCRIPTION_ TEXT NOT NULL DEFAULT '',
	IS_SYSTEM_ INTEGER NOT NULL DEFAULT 1 CHECK (IS_SYSTEM_ IN (0, 1)),
	CREATED_AT_ TEXT NOT NULL,
	UPDATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT
);

CREATE TABLE IF NOT EXISTS workflow_stage (
	ID_ TEXT PRIMARY KEY,
	WORKFLOW_ID_ TEXT NOT NULL REFERENCES workflow(ID_),
	STAGE_DEF_ID_ TEXT NOT NULL REFERENCES workflow_stage_def(ID_),
	KEY_ TEXT NOT NULL,
	NAME_ TEXT NOT NULL,
	POSITION_ INTEGER NOT NULL,
	IS_START_ INTEGER NOT NULL DEFAULT 0 CHECK (IS_START_ IN (0, 1)),
	IS_END_ INTEGER NOT NULL DEFAULT 0 CHECK (IS_END_ IN (0, 1)),
	UNIQUE (WORKFLOW_ID_, KEY_)
);

CREATE TABLE IF NOT EXISTS workflow_status (
	ID_ TEXT PRIMARY KEY,
	WORKFLOW_ID_ TEXT NOT NULL REFERENCES workflow(ID_),
	STAGE_ID_ TEXT REFERENCES workflow_stage(ID_),
	STATUS_DEF_ID_ TEXT NOT NULL REFERENCES workflow_status_def(ID_),
	KEY_ TEXT NOT NULL,
	NAME_ TEXT NOT NULL,
	COLUMN_KEY_ TEXT NOT NULL CHECK (COLUMN_KEY_ IN ('backlog','todo','in_progress','in_review','completed')),
	POSITION_ INTEGER NOT NULL,
	IS_START_ INTEGER NOT NULL DEFAULT 0 CHECK (IS_START_ IN (0, 1)),
	IS_TERMINAL_ INTEGER NOT NULL DEFAULT 0 CHECK (IS_TERMINAL_ IN (0, 1)),
	IS_ACTIVE_ INTEGER NOT NULL DEFAULT 1 CHECK (IS_ACTIVE_ IN (0, 1)),
	REVIEW_REQUIRED_ INTEGER NOT NULL DEFAULT 0 CHECK (REVIEW_REQUIRED_ IN (0, 1)),
	UNIQUE (WORKFLOW_ID_, KEY_)
);

CREATE TABLE IF NOT EXISTS workflow_transition (
	ID_ TEXT PRIMARY KEY,
	WORKFLOW_ID_ TEXT NOT NULL REFERENCES workflow(ID_),
	FROM_STAGE_ID_ TEXT NOT NULL REFERENCES workflow_stage(ID_),
	FROM_STATUS_ID_ TEXT NOT NULL REFERENCES workflow_status(ID_),
	TO_STAGE_ID_ TEXT NOT NULL REFERENCES workflow_stage(ID_),
	TO_STATUS_ID_ TEXT NOT NULL REFERENCES workflow_status(ID_),
	ACTION_KEY_ TEXT NOT NULL,
	NAME_ TEXT NOT NULL,
	ACTOR_TYPE_ TEXT NOT NULL CHECK (ACTOR_TYPE_ IN ('human','agent','system')),
	REQUIRES_REVIEW_ INTEGER NOT NULL DEFAULT 0 CHECK (REQUIRES_REVIEW_ IN (0, 1)),
	POSITION_ INTEGER NOT NULL DEFAULT 0,
	CREATED_AT_ TEXT NOT NULL,
	IS_ACTIVE_ INTEGER NOT NULL DEFAULT 1 CHECK (IS_ACTIVE_ IN (0, 1))
);

CREATE TABLE IF NOT EXISTS project (
	ID_ TEXT PRIMARY KEY,
	PARENT_ID_ TEXT REFERENCES project(ID_),
	SLUG_ TEXT NOT NULL,
	KEY_ TEXT NOT NULL DEFAULT '',
	NAME_ TEXT NOT NULL,
	DESCRIPTION_ TEXT NOT NULL DEFAULT '',
	PATH_ TEXT NOT NULL UNIQUE,
	DEPTH_ INTEGER NOT NULL DEFAULT 0,
	POSITION_ REAL NOT NULL DEFAULT 0,
	VISIBILITY_ TEXT NOT NULL DEFAULT 'workspace' CHECK (VISIBILITY_ IN ('private','team','workspace')),
	DEFAULT_WORKFLOW_ID_ TEXT NOT NULL REFERENCES workflow(ID_),
	ARCHIVED_AT_ TEXT,
	CREATED_BY_ TEXT,
	UPDATED_BY_ TEXT,
	CREATED_AT_ TEXT NOT NULL,
	UPDATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT,
	UNIQUE (PARENT_ID_, SLUG_)
);

CREATE TABLE IF NOT EXISTS project_closure (
	ANCESTOR_ID_ TEXT NOT NULL REFERENCES project(ID_),
	DESCENDANT_ID_ TEXT NOT NULL REFERENCES project(ID_),
	DEPTH_ INTEGER NOT NULL,
	PRIMARY KEY (ANCESTOR_ID_, DESCENDANT_ID_)
);

CREATE TABLE IF NOT EXISTS project_permission (
	ID_ TEXT PRIMARY KEY,
	PROJECT_ID_ TEXT NOT NULL REFERENCES project(ID_),
	PRINCIPAL_TYPE_ TEXT NOT NULL CHECK (PRINCIPAL_TYPE_ IN ('user','team')),
	PRINCIPAL_ID_ TEXT NOT NULL,
	ROLE_ TEXT NOT NULL CHECK (ROLE_ IN ('owner','admin','maintainer','developer','reviewer','viewer')),
	INHERIT_TO_CHILDREN_ INTEGER NOT NULL DEFAULT 1 CHECK (INHERIT_TO_CHILDREN_ IN (0, 1)),
	CREATED_BY_ TEXT,
	CREATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT
);

CREATE TABLE IF NOT EXISTS project_desktop_binding (
	ID_ TEXT PRIMARY KEY,
	PROJECT_ID_ TEXT NOT NULL REFERENCES project(ID_),
	DEVICE_ID_ TEXT NOT NULL,
	CURRENT_USER_ID_ TEXT NOT NULL DEFAULT '',
	LOCAL_PROJECT_ID_ TEXT NOT NULL,
	LOCAL_DISPLAY_NAME_ TEXT NOT NULL,
	SYNC_POLICY_ TEXT NOT NULL DEFAULT 'future' CHECK (SYNC_POLICY_ IN ('future','select','all')),
	CONTROL_MODE_ TEXT NOT NULL DEFAULT 'dispatch' CHECK (CONTROL_MODE_ IN ('dispatch','observe','disabled')),
	STATUS_ TEXT NOT NULL DEFAULT 'active' CHECK (STATUS_ IN ('active','paused','error')),
	LAST_REMOTE_REVISION_ INTEGER NOT NULL DEFAULT 0,
	SYNC_SINCE_AT_ TEXT,
	CREATED_BY_ TEXT,
	UPDATED_BY_ TEXT,
	CREATED_AT_ TEXT NOT NULL,
	UPDATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT
);

CREATE TABLE IF NOT EXISTS project_binding_issue (
	BINDING_ID_ TEXT NOT NULL,
	ISSUE_ID_ TEXT NOT NULL,
	SOURCE_ TEXT NOT NULL DEFAULT 'select' CHECK (SOURCE_ IN ('select','dispatch','desktop_sync')),
	CREATED_AT_ TEXT NOT NULL,
	PRIMARY KEY (BINDING_ID_, ISSUE_ID_)
);

CREATE TABLE IF NOT EXISTS agent (
	ID_ TEXT PRIMARY KEY,
	AGENT_KEY_ TEXT NOT NULL UNIQUE,
	NAME_ TEXT NOT NULL,
	DESCRIPTION_ TEXT NOT NULL DEFAULT '',
	ROLE_ TEXT NOT NULL DEFAULT '',
	MODEL_ TEXT,
	MODEL_VERSION_ TEXT,
	ENABLED_ INTEGER NOT NULL DEFAULT 1 CHECK (ENABLED_ IN (0, 1)),
	CREATED_BY_ TEXT,
	UPDATED_BY_ TEXT,
	CREATED_AT_ TEXT NOT NULL,
	UPDATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT
);

CREATE TABLE IF NOT EXISTS review (
	ID_ TEXT PRIMARY KEY,
	ISSUE_ID_ TEXT NOT NULL,
	AGENT_RUN_ID_ TEXT,
	REVIEW_TYPE_ TEXT NOT NULL CHECK (REVIEW_TYPE_ IN ('agent_output','peer')),
	REVIEWER_ID_ TEXT,
	STATUS_ TEXT NOT NULL CHECK (STATUS_ IN ('pending','approved','changes_requested','rejected')),
	REQUESTED_BY_ TEXT,
	REQUESTED_AT_ TEXT NOT NULL,
	SUBMITTED_AT_ TEXT,
	SUMMARY_ TEXT NOT NULL DEFAULT '',
	CREATED_AT_ TEXT NOT NULL,
	UPDATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT
);

CREATE TABLE IF NOT EXISTS issue (
	ID_ TEXT PRIMARY KEY,
	PROJECT_ID_ TEXT NOT NULL REFERENCES project(ID_),
	WORKFLOW_ID_ TEXT NOT NULL REFERENCES workflow(ID_),
	STAGE_ID_ TEXT NOT NULL REFERENCES workflow_stage(ID_),
	STATUS_ID_ TEXT NOT NULL REFERENCES workflow_status(ID_),
	TITLE_ TEXT NOT NULL CHECK (length(trim(TITLE_)) > 0),
	DESCRIPTION_ TEXT NOT NULL DEFAULT '',
	PRIORITY_ TEXT NOT NULL CHECK (PRIORITY_ IN ('high','medium','low')),
	SEVERITY_ TEXT NOT NULL DEFAULT 'medium' CHECK (SEVERITY_ IN ('critical','high','medium','low')),
	POSITION_ REAL NOT NULL,
	ASSIGNEE_ID_ TEXT,
	WORKER_TYPE_ TEXT CHECK (WORKER_TYPE_ IN ('human','agent')),
	WORKER_ID_ TEXT,
	WORKER_AGENT_ TEXT,
	REVIEWER_ID_ TEXT,
	REVIEW_REQUIRED_ INTEGER NOT NULL DEFAULT 0 CHECK (REVIEW_REQUIRED_ IN (0, 1)),
	ACTIVE_REVIEW_ID_ TEXT REFERENCES review(ID_),
	ACTIVE_RUN_ID_ TEXT,
	REVISION_ INTEGER NOT NULL DEFAULT 0,
	CREATED_BY_ TEXT,
	UPDATED_BY_ TEXT,
	CREATED_BY_AGENT_ TEXT,
	UPDATED_BY_AGENT_ TEXT,
	CREATED_AT_ TEXT NOT NULL,
	UPDATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT,
	CHECK (
		WORKER_TYPE_ IS NULL OR
		(WORKER_TYPE_ = 'human' AND WORKER_ID_ IS NOT NULL AND WORKER_AGENT_ IS NULL) OR
		(WORKER_TYPE_ = 'agent' AND WORKER_AGENT_ IS NOT NULL AND WORKER_ID_ IS NULL)
	)
);

CREATE TABLE IF NOT EXISTS issue_label (
	ID_ TEXT PRIMARY KEY,
	PROJECT_ID_ TEXT NOT NULL REFERENCES project(ID_),
	KEY_ TEXT NOT NULL,
	NAME_ TEXT NOT NULL,
	COLOR_ TEXT NOT NULL DEFAULT '',
	CREATED_BY_ TEXT,
	UPDATED_BY_ TEXT,
	CREATED_AT_ TEXT NOT NULL,
	UPDATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT,
	UNIQUE (PROJECT_ID_, KEY_)
);

CREATE TABLE IF NOT EXISTS issue_label_link (
	ISSUE_ID_ TEXT NOT NULL REFERENCES issue(ID_),
	LABEL_ID_ TEXT NOT NULL REFERENCES issue_label(ID_),
	PRIMARY KEY (ISSUE_ID_, LABEL_ID_)
);

CREATE TABLE IF NOT EXISTS issue_attachment (
	ID_ TEXT PRIMARY KEY,
	ISSUE_ID_ TEXT NOT NULL REFERENCES issue(ID_),
	KIND_ TEXT NOT NULL DEFAULT '',
	NAME_ TEXT NOT NULL DEFAULT '',
	MIME_TYPE_ TEXT NOT NULL DEFAULT '',
	SIZE_BYTES_ INTEGER NOT NULL DEFAULT 0,
	URL_ TEXT,
	TEXT_ TEXT,
	METADATA_JSON_ TEXT NOT NULL DEFAULT '{}',
	CREATED_BY_ TEXT,
	CREATED_BY_AGENT_ TEXT,
	CREATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT
);

CREATE TABLE IF NOT EXISTS issue_dependency (
	ID_ TEXT PRIMARY KEY,
	FROM_ISSUE_ID_ TEXT NOT NULL REFERENCES issue(ID_),
	TO_ISSUE_ID_ TEXT NOT NULL REFERENCES issue(ID_),
	TYPE_ TEXT NOT NULL DEFAULT 'blocks',
	CREATED_BY_ TEXT,
	CREATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT
);

CREATE TABLE IF NOT EXISTS issue_automation (
	ID_ TEXT PRIMARY KEY,
	ISSUE_ID_ TEXT NOT NULL REFERENCES issue(ID_),
	EXTERNAL_AUTOMATION_ID_ TEXT,
	ENABLED_ INTEGER NOT NULL DEFAULT 0 CHECK (ENABLED_ IN (0, 1)),
	CRON_ TEXT,
	TIMEZONE_ TEXT,
	MESSAGE_ TEXT,
	CREATED_BY_ TEXT,
	UPDATED_BY_ TEXT,
	CREATED_AT_ TEXT NOT NULL,
	UPDATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT
);

CREATE TABLE IF NOT EXISTS agent_run (
	ID_ TEXT PRIMARY KEY,
	ISSUE_ID_ TEXT NOT NULL REFERENCES issue(ID_),
	AGENT_ID_ TEXT REFERENCES agent(ID_),
	WORKER_AGENT_ TEXT,
	DELEGATED_BY_ TEXT,
	CHAT_ID_ TEXT,
	RUN_ID_ TEXT,
	SESSION_ID_ TEXT,
	STATUS_ TEXT NOT NULL CHECK (STATUS_ IN ('queued','running','succeeded','failed','cancelled','completed')),
	CONFIDENCE_ REAL,
	INPUT_TOKENS_ INTEGER,
	OUTPUT_TOKENS_ INTEGER,
	COST_MICROS_ INTEGER,
	STARTED_AT_ TEXT,
	FINISHED_AT_ TEXT,
	ERROR_MESSAGE_ TEXT,
	CREATED_AT_ TEXT NOT NULL,
	UPDATED_AT_ TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS agent_tool_call (
	ID_ TEXT PRIMARY KEY,
	AGENT_RUN_ID_ TEXT NOT NULL REFERENCES agent_run(ID_),
	TOOL_NAME_ TEXT NOT NULL,
	TOOL_TYPE_ TEXT NOT NULL DEFAULT '',
	STATUS_ TEXT NOT NULL DEFAULT '',
	INPUT_JSON_ TEXT NOT NULL DEFAULT '{}',
	OUTPUT_JSON_ TEXT NOT NULL DEFAULT '{}',
	STARTED_AT_ TEXT,
	FINISHED_AT_ TEXT,
	ERROR_MESSAGE_ TEXT
);

CREATE TABLE IF NOT EXISTS review_comment (
	ID_ TEXT PRIMARY KEY,
	REVIEW_ID_ TEXT NOT NULL REFERENCES review(ID_),
	ISSUE_ID_ TEXT NOT NULL REFERENCES issue(ID_),
	AUTHOR_ID_ TEXT,
	AUTHOR_AGENT_ TEXT,
	BODY_ TEXT NOT NULL,
	ANCHOR_JSON_ TEXT NOT NULL DEFAULT '{}',
	CREATED_AT_ TEXT NOT NULL,
	UPDATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT
);

CREATE TABLE IF NOT EXISTS board (
	ID_ TEXT PRIMARY KEY,
	PROJECT_ID_ TEXT NOT NULL REFERENCES project(ID_),
	KEY_ TEXT NOT NULL,
	NAME_ TEXT NOT NULL,
	CREATED_BY_ TEXT,
	UPDATED_BY_ TEXT,
	CREATED_AT_ TEXT NOT NULL,
	UPDATED_AT_ TEXT NOT NULL,
	DELETED_AT_ TEXT
);

CREATE TABLE IF NOT EXISTS board_meta (
	BOARD_ID_ TEXT NOT NULL,
	KEY_ TEXT NOT NULL,
	VALUE_ TEXT NOT NULL,
	PRIMARY KEY (BOARD_ID_, KEY_)
);

CREATE TABLE IF NOT EXISTS event_log (
	ID_ INTEGER PRIMARY KEY AUTOINCREMENT,
	BOARD_ID_ TEXT NOT NULL,
	PROJECT_ID_ TEXT,
	ISSUE_ID_ TEXT,
	REVISION_ INTEGER NOT NULL,
	EVENT_TYPE_ TEXT NOT NULL,
	ACTOR_ID_ TEXT,
	ACTOR_AGENT_ TEXT,
	PAYLOAD_JSON_ TEXT NOT NULL DEFAULT '{}',
	CREATED_AT_ TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS desktop_client (
	SESSION_ID_ TEXT PRIMARY KEY,
	DEVICE_ID_ TEXT,
	CURRENT_USER_ID_ TEXT,
	CURRENT_USER_NAME_ TEXT,
	CAPABILITIES_JSON_ TEXT NOT NULL DEFAULT '[]',
	SELECTED_PROJECT_ID_ TEXT,
	CONNECTED_AT_ TEXT NOT NULL,
	LAST_SEEN_AT_ TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_project_parent_position
	ON project(PARENT_ID_, POSITION_, ID_)
	WHERE DELETED_AT_ IS NULL;

CREATE INDEX IF NOT EXISTS idx_project_closure_descendant
	ON project_closure(DESCENDANT_ID_, ANCESTOR_ID_);

CREATE INDEX IF NOT EXISTS idx_project_permission_project
	ON project_permission(PROJECT_ID_, PRINCIPAL_TYPE_, PRINCIPAL_ID_)
	WHERE DELETED_AT_ IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_project_desktop_binding_unique_active
	ON project_desktop_binding(PROJECT_ID_, DEVICE_ID_, LOCAL_PROJECT_ID_)
	WHERE DELETED_AT_ IS NULL;

CREATE INDEX IF NOT EXISTS idx_project_desktop_binding_project
	ON project_desktop_binding(PROJECT_ID_, STATUS_, UPDATED_AT_)
	WHERE DELETED_AT_ IS NULL;

CREATE INDEX IF NOT EXISTS idx_issue_project_status_position
	ON issue(PROJECT_ID_, STATUS_ID_, POSITION_, ID_)
	WHERE DELETED_AT_ IS NULL;

CREATE INDEX IF NOT EXISTS idx_issue_workflow_stage_status
	ON issue(WORKFLOW_ID_, STAGE_ID_, STATUS_ID_)
	WHERE DELETED_AT_ IS NULL;

CREATE INDEX IF NOT EXISTS idx_issue_active_run
	ON issue(ACTIVE_RUN_ID_)
	WHERE ACTIVE_RUN_ID_ IS NOT NULL AND DELETED_AT_ IS NULL;

CREATE INDEX IF NOT EXISTS idx_issue_automation_issue
	ON issue_automation(ISSUE_ID_)
	WHERE DELETED_AT_ IS NULL;

CREATE INDEX IF NOT EXISTS idx_issue_attachment_issue
	ON issue_attachment(ISSUE_ID_, CREATED_AT_, ID_)
	WHERE DELETED_AT_ IS NULL;

CREATE INDEX IF NOT EXISTS idx_issue_label_project
	ON issue_label(PROJECT_ID_, NAME_, ID_)
	WHERE DELETED_AT_ IS NULL;

CREATE INDEX IF NOT EXISTS idx_issue_dependency_from
	ON issue_dependency(FROM_ISSUE_ID_, TO_ISSUE_ID_, ID_)
	WHERE DELETED_AT_ IS NULL;

CREATE INDEX IF NOT EXISTS idx_issue_dependency_to
	ON issue_dependency(TO_ISSUE_ID_, FROM_ISSUE_ID_, ID_)
	WHERE DELETED_AT_ IS NULL;

CREATE INDEX IF NOT EXISTS idx_review_issue
	ON review(ISSUE_ID_, UPDATED_AT_, ID_)
	WHERE DELETED_AT_ IS NULL;

CREATE INDEX IF NOT EXISTS idx_review_comment_issue
	ON review_comment(ISSUE_ID_, CREATED_AT_, ID_)
	WHERE DELETED_AT_ IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_run_issue
	ON agent_run(ISSUE_ID_, CREATED_AT_, ID_);

CREATE INDEX IF NOT EXISTS idx_agent_tool_call_run
	ON agent_tool_call(AGENT_RUN_ID_, STARTED_AT_, ID_);

CREATE INDEX IF NOT EXISTS idx_agent_run_external
	ON agent_run(RUN_ID_, CHAT_ID_, STATUS_);

CREATE INDEX IF NOT EXISTS idx_event_log_board_revision
	ON event_log(BOARD_ID_, REVISION_);

CREATE INDEX IF NOT EXISTS idx_workflow_transition_from
	ON workflow_transition(WORKFLOW_ID_, FROM_STAGE_ID_, FROM_STATUS_ID_, ACTION_KEY_);
